print("""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.""")

num1 = 1
num2 = 2
result = num1 + num2
limit = 4000000
evenSum = 0 

while (result <= limit):     
    num1 = num2
    num2 = result
    result = num1 + num2
    
    if result % 2 == 0: 
        evenSum += result

print(evenSum + 2)
        